### ISSUE TITLE
NotNullChecker.cs is not an editor script, but it uses the UnityEditor namespace, causing compilation errors.

### ISSUE THREAD

**Issue by jacobkjaer** [redbluegames/unity-notnullattribute#5]
It seems that, without too much testing, moving the script to the Editor folder solves the issue.

Kudos on the plugin, really like it.

**Comment by edwardrowe** [comment]
Thanks! I think this is a change we've made locally and haven't pushed to the repo. Thanks for reporting this!

**Comment by edwardrowe** [comment]
So I've merged a fix for this, but I'm going to put together a new release in a bit. The updated UnityPackage may not recognize this as a fix because I moved the files and I'm not sure it will update file paths for already installed files... so to fix that:

If you've installed an older version of this plugin, you may need to move NotNullChecker to the Editor folder (RedBlueGames/NotNulAttribute/Editor)

**Comment by jacobkjaer** [comment]
Cheers, looking forward to the next version :-)
